ITB.Kusys.Cse.Project.WebUI/Models/DashboardModel.cs
namespace ITB.Kusys.Cse.Project.WebUI.Models
{
    public class DashboardModel
    {
        public int StudentCount { get; set; }
        public int Course { get; set; }
        public int CourseCategory { get; set; }
    }
}

ITB.Kusys.Cse.Project.WebUI/Controllers/CourseController.cs
using ITB.Cse.Project.WebUI.Attribute;
using ITB.Kusys.Cse.Project.Bussiness.Abstract.Course;
using ITB.Kusys.Cse.Project.Entities.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace ITB.Cse.Project.WebUI.Controllers
{

    [Authorations]
    [AdminAtt]
    public class CourseController : Controller
    {
        private readonly ICourseService _courseService;

        public CourseController(ICourseService courseService)
        {
            _courseService = courseService;
        }

        public IActionResult Index()
        {
            var data = _courseService.GetAllCourses().ToList();
            return View(data);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Course model)
        {          
            try
            {
                model.CreatedTime = DateTime.Now;
                model.ModifiedTime = DateTime.Now;
                var result = _courseService.AddCourse(model);
                return Redirect("/Course/Index");

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error",ex.Message);
                return View();

            }

        }

        [HttpPost]
        public IActionResult Delete(int Id)
        {
            try
            {
               var course = _courseService.GetById(Id);
                var result = _courseService.DeleteCourse(course);
                return Redirect("/Course/Index");

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error", ex.Message);
                return View();

            }

        }


    }
}

ITB.Kusys.Cse.Project.WebUI/Controllers/HomeController.cs
using ITB.Cse.Project.WebUI.Attribute;
using ITB.Kusys.Cse.Project.Bussiness.Abstract.Course;
using ITB.Kusys.Cse.Project.Bussiness.Abstract.Login;
using ITB.Kusys.Cse.Project.Bussiness.Abstract.Student;
using ITB.Kusys.Cse.Project.Bussiness.Abstract.StudentCourseService;
using ITB.Kusys.Cse.Project.WebUI.Models;
using Microsoft.AspNetCore.Mvc;

namespace ITB.Cse.Project.WebUI.Controllers
{

    [Authorations]
    public class HomeController : Controller
    {
        private readonly IStudentService _studentService;
        private readonly ICourseService _courseService;
        private readonly IStudentCourseService _studentCourseService;

        public HomeController(IStudentService studentService,
            IStudentCourseService studentCourseService,
            ICourseService courseService)
        {
            _studentService = studentService;
            _studentCourseService = studentCourseService;
            _courseService = courseService;
        }
        public IActionResult Index()
        {

            return View(new DashboardModel
            {
                Course = _courseService.GetAllCourses().Count(),
                StudentCount = _studentService.GetAllStudents().Count(),
                CourseCategory = _studentService.GetAllStudents().Count(),
            });
        }
    }
}

ITB.Kusys.Cse.Project.WebUI/Controllers/LoginController.cs
using ITB.Cse.Project.WebUI.Attribute;
using ITB.Cse.Project.WebUI.Sessions;
using ITB.Kusys.Cse.Project.Bussiness.Abstract.Login;
using ITB.Kusys.Cse.Project.Bussiness.Abstract.User;
using ITB.Kusys.Cse.Project.Entities.Dto;
using Microsoft.AspNetCore.Mvc;

namespace ITB.Cse.Project.WebUI.Controllers
{


    public class LoginController : Controller
    {
        private readonly ILoginService _loginService;
        private readonly IUserService _userService;

        public LoginController(ILoginService loginService, IUserService userService)
        {
            _loginService = loginService;
            _userService = userService;
        }

        [LoginAtt]
        [Route("login")]
        public IActionResult Index()
        {
            return View();
        }

        [LoginAtt]
        [Route("login")]
        [HttpPost]
        public IActionResult Index(UserLoginDto model)
        {
            var login = _loginService.Login(model);           
            Session.Set("login", login.Data);
            return Redirect("/");
        }

        [Authorations]
        public IActionResult LogOut()
        {
            Session.Remove("login");
            return Redirect("/login");
        }

    


    }
}

ITB.Kusys.Cse.Project.WebUI/Controllers/StudentController.cs
using ITB.Cse.Project.WebUI.Attribute;
using ITB.Cse.Project.WebUI.Sessions;
using ITB.Kusys.Cse.Project.Bussiness.Abstract.Course;
using ITB.Kusys.Cse.Project.Bussiness.Abstract.Login;
using ITB.Kusys.Cse.Project.Bussiness.Abstract.Student;
using ITB.Kusys.Cse.Project.Bussiness.Abstract.StudentCourseService;
using ITB.Kusys.Cse.Project.Bussiness.Concrete.Login;
using ITB.Kusys.Cse.Project.Entities.Concrete;
using ITB.Kusys.Cse.Project.Entities.Dto;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ITB.Cse.Project.WebUI.Controllers
{

    [Authorations]
    public class StudentController : Controller
    {
        private readonly IStudentService _studentService;
        private readonly ICourseService _courseService;
        private readonly ILoginService _loginService;
        private readonly IStudentCourseService _studentCourseService;

        public StudentController(IStudentService studentService,
            IStudentCourseService studentCourseService,
            ILoginService loginManager,
            ICourseService courseService)
        {
            _studentService = studentService;
            _studentCourseService = studentCourseService;
            _loginService = loginManager;
            _courseService = courseService;
        }


        [Authorations]
        public IActionResult Index()
        {
            return View(_studentService.GetAllStudents());
        }
    
        [AdminAtt]
        public IActionResult Create()
        {
            ViewBag.Courses = _courseService.GetAllCourses().ToList();
            return View();
        }

        [HttpPost]
        [AdminAtt]
        public IActionResult Create(Student model, string password, List<int> tags)
        {
            var data = _studentService.AddStudent(model);
            if (data <= 0)
            {
                return View("Error");
            }
            var student = _studentService.GetByMail(model.Email);
            if (!tags.Any()) return Redirect("/student-list");
            foreach (var mapping in tags.Select(tagId => new StudentCourse()
            {
                CourseId = tagId,
                StudentId = student.Id
            }))
            {
                _studentCourseService.Insert(mapping);
            }
            UserRegisterDto userRegisterDto = new UserRegisterDto()
            {
                Email = model.Email,
                Password = password,
                Username = model.FirstName + model.LastName,
            };
            var register = _loginService.Register(userRegisterDto, 2);

            return Redirect("/Student/Index");
        }


        [UserAtt]
        public IActionResult StudentCourseList()
        {
            var currentUser = _studentService.GetByMail(Session.User.Email);
            var students = _studentService.Queryable()
          .Include(s => s.StudentCourse)
          .ThenInclude(sc => sc.Course)
          .ToList().SingleOrDefault(x => x.Id == currentUser.Id);

            var studentViewModels = new List<StudentViewModel>
        {
            new StudentViewModel
            {
                CourseName = students.StudentCourse
                    .Select(sc => $"{sc.Course.Name}").ToList()
            }
        };


            return View(studentViewModels);
        }




    }
}

ITB.Kusys.Cse.Project.WebUI/Controllers/UserController.cs
using ITB.Cse.Project.WebUI.Attribute;
using ITB.Kusys.Cse.Project.Bussiness.Abstract.User;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ITB.Cse.Project.WebUI.Controllers
{

    [Authorations]
    public class UserController : Controller
    {
        private IUserService _userService;
        public UserController(IUserService userService)
        {
            _userService = userService;
        }

        [Route("list")]
        public IActionResult Index()
        {
            var data = _userService.GetAllUser().Include(x => x.Role).ToList();
            return View(data);
        }
    }
}

ITB.Kusys.Cse.Project.WebUI/Views/Course/Create.cshtml
@using ITB.Kusys.Cse.Project.Entities.Concrete
@model Course
@{
    ViewData["Title"] = "Course Create";
}

<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Course /</span> Edit</h4>
    <div class="row">
        <div class="col-xxl">
            <div class="card mb-12">
                <div class="card-body">
                    @using (Html.BeginForm("Create", "Course", FormMethod.Post))
                    {
                        @Html.ValidationSummary(false)
                        <form>                         

                            <div class="row mb-3">
                                <label class="col-sm-2 col-form-label" for="Name">Name</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" name="Name" id="Name"/>
                                </div>
                            </div>

                            <div class="row justify-content-end">
                                <div class="col-sm-10">
                                    <button type="submit" class="btn btn-primary">Save</button>
                                    <a href="/Course/Index" class="btn btn-secondary">Back</a>
                                </div>
                            </div>
                        </form>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

ITB.Kusys.Cse.Project.WebUI/Views/Course/Index.cshtml
@model List<ITB.Kusys.Cse.Project.Entities.Concrete.Course>
@{
    ViewData["Title"] = "Course List";
    Layout = "_Layout";
}

<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Course /</span> Course List</h4>
    <div class="card">
        <h5 class="card-header"><a href="/Course/Create" class="btn btn-secondary">New Course</a></h5>
        <div class="table-responsive text-nowrap">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>CourseId</th>
                    <th>Name</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody class="table-border-bottom-0">
                @if (Model.Count > 0)
                {
                    foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                <i class="fab fa-angular fa-lg text-danger me-3"></i> <strong>@item.Id</strong>
                            </td>
                            <td>@item.Name</td>
                            <td>                             
                                <a href="/Course/Delete?Id=@item.Id" class="btn rounded-pill btn-icon btn-outline-danger">
                                    <span class="tf-icons bx bx-trash-alt"></span>
                                </a>
                            </td>
                        </tr>
                    }
                }
                </tbody>
            </table>
        </div>
    </div>
</div>

ITB.Kusys.Cse.Project.WebUI/Views/Login/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Star Admin2 </title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="/assets/vendors/feather/feather.css">
    <link rel="stylesheet" href="/assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="/assets/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" href="/assets/vendors/typicons/typicons.css">
    <link rel="stylesheet" href="/assets/vendors/simple-line-icons/css/simple-line-icons.css">
    <link rel="stylesheet" href="/assets/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="/assets/css/vertical-layout-light/style.css">
    <!-- endinject -->
    <link rel="shortcut icon" href="/assets/images/favicon.png" />
</head>

<body>
    <div class="container-scroller">
        <div class="container-fluid page-body-wrapper full-page-wrapper">
            <div class="content-wrapper d-flex align-items-center auth px-0">
                <div class="row w-100 mx-0">
                    <div class="col-lg-4 mx-auto">
                        <div class="auth-form-light text-left py-5 px-4 px-sm-5">
                            <div class="brand-logo">
                                <img src="/assets/images/logo.svg" alt="logo">
                            </div>
                            @using (Html.BeginForm("Index", "Login", FormMethod.Post))
                            {

                                <div clas s="form-group">
                                    <input type="email" class="form-control form-control-lg" id="Email" name="Email" placeholder="Email">
                                </div>
                                <div class="form-group">
                                    <input type="password" class="form-control form-control-lg" id="Password" name="Password" placeholder="Password">
                                </div>
                                <div class="mt-3">
                                    <button class="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn" action="SUBMIT">SIGN IN</button>
                                </div>



                            }
                        </div>
                    </div>
                </div>
            </div>
            <!-- content-wrapper ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="/assets/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="/assets/vendors/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="/assets/js/off-canvas.js"></script>
    <script src="/assets/js/hoverable-collapse.js"></script>
    <script src="/assets/js/template.js"></script>
    <script src="/assets/js/settings.js"></script>
    <script src="/assets/js/todolist.js"></script>
    <!-- endinject -->
</body>

</html>

ITB.Kusys.Cse.Project.WebUI/Views/Shared/_Layout.cshtml
@using ITB.Cse.Project.WebUI.Sessions;
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Star Admin2 </title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="/assets/vendors/feather/feather.css">
    <link rel="stylesheet" href="/assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="/assets/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" href="/assets/vendors/typicons/typicons.css">
    <link rel="stylesheet" href="/assets/vendors/simple-line-icons/css/simple-line-icons.css">
    <link rel="stylesheet" href="/assets/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="/assets/vendors/datatables.net-bs4/dataTables.bootstrap4.css">
    <link rel="stylesheet" href="/assets/js/select.dataTables.min.css">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="/assets/css/vertical-layout-light/style.css">
    <!-- endinject -->
    <link rel="shortcut icon" href="/assets/images/favicon.png" />
</head>
<body>
    <div class="container-scroller">

        <!-- partial:partials/_navbar.html -->
        <nav class="navbar default-layout col-lg-12 col-12 p-0 fixed-top d-flex align-items-top flex-row">
            <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-start">
                <div class="me-3">
                    <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-bs-toggle="minimize">
                        <span class="icon-menu"></span>
                    </button>
                </div>
                <div>
                    <a class="navbar-brand brand-logo" href="index.html">
                        <img src="/assets/images/logo.svg" alt="logo" />
                    </a>
                    <a class="navbar-brand brand-logo-mini" href="index.html">
                        <img src="/assets/images/logo-mini.svg" alt="logo" />
                    </a>
                </div>
            </div>
            <div class="navbar-menu-wrapper d-flex align-items-top">
                <ul class="navbar-nav">
                    <li class="nav-item font-weight-semibold d-none d-lg-block ms-0">
                        <h1 class="welcome-text">Good Morning, <span class="text-black fw-bold">@Session.User.Username</span></h1>
                        <h3 class="welcome-sub-text">Your performance summary this week </h3>
                    </li>
                </ul>
                <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-bs-toggle="offcanvas">
                    <span class="mdi mdi-menu"></span>
                </button>
            </div>
        </nav>
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <!-- partial:partials/_settings-panel.html -->
            <!-- partial -->
            <!-- partial:partials/_sidebar.html -->
            <nav class="sidebar sidebar-offcanvas" id="sidebar">
                <ul class="nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/">
                            <i class="mdi mdi-grid-large menu-icon"></i>
                            <span class="menu-title">Dashboard</span>
                        </a>
                    </li>
                    <li class="nav-item nav-category">Genel İşlemler</li>
                    <li class="nav-item">
                        <a class="nav-link" data-bs-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
                            <i class="menu-icon mdi mdi-floor-plan"></i>
                            <span class="menu-title">İşlemler</span>
                            <i class="menu-arrow"></i>
                        </a>
                        <div class="collapse" id="ui-basic">
                            <ul class="nav flex-column sub-menu">
                                <li class="nav-item"> <a class="nav-link" href="/Student/StudentCourseList">Kurslarım</a></li>
                            </ul>
                        </div>
                    </li>
                    @if (Session.User.Role.Name.ToLower() == "admin")
                    {
                        <li class="nav-item nav-category">Admin İşlemleri</li>
                        <li class="nav-item">
                            <a class="nav-link" data-bs-toggle="collapse" href="#form-elements" aria-expanded="false" aria-controls="form-elements">
                                <i class="menu-icon mdi mdi-card-text-outline"></i>
                                <span class="menu-title">Admin İşlemleri</span>
                                <i class="menu-arrow"></i>
                            </a>
                            <div class="collapse" id="form-elements">
                                <ul class="nav flex-column sub-menu">
                                    <li class="nav-item"><a class="nav-link" href="/Student/Index">Öğrenciler</a></li>
                                    <li class="nav-item"><a class="nav-link" href="/Student/Create">Öğrenci Ekle</a></li>
                                    <li class="nav-item"><a class="nav-link" href="/Course/Index">Kurslar</a></li>
                                    <li class="nav-item"><a class="nav-link" href="/Course/Create">Kurs Ekle</a></li>
                                </ul>
                            </div>
                        </li>
                    }

                    <li class="nav-item nav-category">
                        <a href="/Login/LogOut" class="btn btn-primary text-white me-0"><i class="icon-download"></i> Çıkış Yap</a>
                    </li>


                </ul>
            </nav>

            @RenderBody()
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="/assets/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="/assets/vendors/chart./Chart.min.js"></script>
    <script src="/assets/vendors/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
    <script src="/assets/vendors/progressbar./assets/js/progressbar.min.js"></script>

    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="/assets/js/off-canvas.js"></script>
    <script src="/assets/js/hoverable-collapse.js"></script>
    <script src="/assets/js/template.js"></script>
    <script src="/assets/js/settings.js"></script>
    <script src="/assets/js/todolist.js"></script>
    <!-- endinject -->
    <!-- Custom js for this page-->
    <script src="/assets/js/jquery.cookie.js" type="text/javascript"></script>
    <script src="/assets/js/dashboard.js"></script>
    <script src="/assets/js/Chart.roundedBarCharts.js"></script>
    <!-- End custom js for this page-->
</body>

</html>

ITB.Kusys.Cse.Project.WebUI/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html
    lang="en"
    class="light-style customizer-hide"
    dir="ltr">
<head>
    <meta charset="utf-8"/>
    <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0"/>

    <title>Kusys Login</title>
    <link rel="preconnect" href="https://fonts.googleapis.com"/>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
    <link
        href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
        rel="stylesheet"/>

    <link rel="stylesheet" href="assets/vendor/fonts/boxicons.css"/>
    <link rel="stylesheet" href="assets/vendor/css/core.css" class="template-customizer-core-css"/>
    <link rel="stylesheet" href="assets/vendor/css/theme-default.css" class="template-customizer-theme-css"/>
    <link rel="stylesheet" href="assets/css/demo.css"/>
    <link rel="stylesheet" href="assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css"/>
    <link rel="stylesheet" href="assets/vendor/css/pages/page-auth.css"/>
    <script src="assets/vendor/js/helpers.js"></script>
    <script src="assets/js/config.js"></script>
</head>
<body>
<div class="container-xxl">
    <div class="authentication-wrapper authentication-basic container-p-y">
        <div class="authentication-inner">
            @RenderBody()
        </div>
    </div>
</div>




<script src="assets/vendor/libs/jquery/jquery.js"></script>
<script src="assets/vendor/libs/popper/popper.js"></script>
<script src="assets/vendor/js/bootstrap.js"></script>
<script src="assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>
<script src="assets/vendor/js/menu.js"></script>
<script src="assets/js/main.js"></script>
<script async defer src="https://buttons.github.io/buttons.js"></script>
</body>
</html>

ITB.Kusys.Cse.Project.WebUI/Views/Student/Create.cshtml
@using ITB.Kusys.Cse.Project.Entities.Concrete
@model Student
@{
    ViewData["Title"] = "Student Create";
}

<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Student /</span> Create</h4>
    <div class="row">
        <div class="col-xxl">
            <div class="card mb-12">
                <div class="card-body">
                    @using (Html.BeginForm("Create", "Student", FormMethod.Post))
                    {
                        @Html.ValidationSummary(false)
                        <span class="text-danger field-validation-error d-none" data-valmsg-replace="true" id="length-trIdentity-validation-error">Must be 11 characters!</span><br/>
                        <span class="text-danger custom-hidden field-validation-error d-none" data-valmsg-replace="true" id="trIdentity-validation-error">Please Enter a Correct TR Number!</span>
                        <form>
                            <div class="row mb-3">
                                <label class="col-sm-2 col-form-label" for="FirstName">First Name</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" name="FirstName" id="FirstName" />
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label class="col-sm-2 col-form-label" for="LastName">Last Name</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" name="LastName" id="LastName" />
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label class="col-sm-2 col-form-label" for="Email">Email</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" name="Email" id="Email"/>
                                </div>
                            </div>
                            
                            <div class="row mb-3">
                                <label class="col-sm-2 col-form-label" for="password">Password</label>
                                <div class="col-sm-10">
                                    <input type="password" class="form-control" name="password" id="password"/>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label class="col-sm-2 col-form-label" for="TrIdentityNumber">Tr Identity Number</label>
                                <div class="col-sm-10">
                                    <input type="number" maxlength="11" class="form-control" name="TrIdentityNumber" id="TrIdentityNumber"/>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label class="col-sm-2 col-form-label" for="BirthDate">Birth Date</label>
                                <div class="col-sm-10">
                                    <input type="date" class="form-control" name="BirthDate" id="BirthDate"/>
                                </div>
                            </div>
                            
                            <div class="form-group select2-drpdwn">
                                    <label for="tags">Course</label>
                                    <select data-placeholder="type tags.." style="height: 120px" multiple class="js-example-basic-multiple col-sm-12" name="tags">
                                        <option value=""></option>
                                        @{
                                            List<Course> tags = ViewBag.Courses;

                                            if (tags != null)
                                            {
                                                foreach (var tag in tags)
                                                {
                                                    <option value="@tag.Id">@tag.Name </option>
                                                } 
                                            }
                                        }
                                    </select>
                            </div>
                            
                            
                            <div class="row justify-content-end">
                                <div class="col-sm-10">
                                    <button type="submit" class="btn btn-primary">Save</button>
                                    <a href="/student-list" class="btn btn-secondary">Back</a>
                                </div>
                            </div>
                        </form>
                    }
                </div>
            </div>
        </div>
    </div>
</div>


<script>
$(".chosen-select").chosen({
  no_results_text: "Tag bulunamadı!"
})
</script>

<script>
    const trIdentityInput = document.getElementById("TrIdentityNumber");
    const lengthErrorSpan = document.getElementById("length-trIdentity-validation-error");
    const validationErrorSpan = document.getElementById("trIdentity-validation-error");
    function VerifyTCNumber(tcno) {
        let tcControl, total;
        tcControl = tcno;
        tcno = tcno.value;
        total = Number(tcno.substring(0, 1)) + Number(tcno.substring(1, 2)) +
            Number(tcno.substring(2, 3)) + Number(tcno.substring(3, 4)) +
            Number(tcno.substring(4, 5)) + Number(tcno.substring(5, 6)) +
            Number(tcno.substring(6, 7)) + Number(tcno.substring(7, 8)) +
            Number(tcno.substring(8, 9)) + Number(tcno.substring(9, 10));
        const strTotal = String(total);
        result = strTotal.substring(strTotal.length, strTotal.length - 1);
    
        return result === tcno.substring(10, 11);
    }
    
    trIdentityInput.addEventListener("input", function () {
        const tcNumber = this.value;
        if (tcNumber.length > 11) {
            this.value = tcNumber.slice(0, 11); 
        }
        if (tcNumber.length !== 11) {
            lengthErrorSpan.classList.remove("d-none");
        } else {
            lengthErrorSpan.classList.add("d-none");
        }
        if (tcNumber.length===0){
            lengthErrorSpan.classList.add("d-none");
            validationErrorSpan.classList.add("d-none");
        }
        if (VerifyTCNumber(this)) {
            validationErrorSpan.classList.add("d-none");
        } else {
            validationErrorSpan.classList.remove("d-none");
        }
    });
</script>

ITB.Kusys.Cse.Project.WebUI/Views/Student/StudentCourseAdd.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
,